use proc_macro2::TokenStream;
use quote::{format_ident, quote};

struct MuxServiceGenerator;

impl prost_build::ServiceGenerator for MuxServiceGenerator {
    fn generate(&mut self, service: prost_build::Service, buf: &mut String) {
        let tokens = generate_service(&service);
        buf.push_str(&tokens.to_string());
        buf.push('\n');
    }
}

/// Configure a `prost_build::Config` with ws-mux service generation enabled.
pub fn configure() -> prost_build::Config {
    let mut config = prost_build::Config::new();
    config.service_generator(Box::new(MuxServiceGenerator));
    config
}

fn generate_service(service: &prost_build::Service) -> TokenStream {
    let mod_name = format_ident!("{}_mux", to_snake_case(&service.name));
    let service_name = &service.name;
    let package = &service.package;
    let module_doc = format!("Generated ws-mux module for the `{service_name}` service.");

    let method_constants = gen_method_constants(service);
    let method_names_array = gen_method_names(service);
    let server_trait = gen_server_trait(service);
    let dispatch_fn = gen_dispatch(service);
    let dispatcher_struct = gen_dispatcher(service);
    let client_struct = gen_client(service);

    quote! {
        #[doc = #module_doc]
        pub mod #mod_name {
            #![allow(unused_imports, clippy::needless_borrows_for_generic_args)]
            use super::*;

            /// Package name.
            pub const PACKAGE: &str = #package;
            /// Service name.
            pub const SERVICE_NAME: &str = #service_name;

            #method_constants
            #method_names_array
            #server_trait
            #dispatch_fn
            #dispatcher_struct
            #client_struct
        }
    }
}

fn gen_method_constants(service: &prost_build::Service) -> TokenStream {
    let consts: Vec<_> = service
        .methods
        .iter()
        .enumerate()
        .map(|(i, method)| {
            let name = format_ident!("METHOD_{}", to_screaming_snake_case(&method.name));
            let idx =
                u8::try_from(i).expect("ws-mux supports at most 256 methods per generated service");
            let comment = format!(
                "Method index for `{}.{}/{}`.",
                service.package, service.name, method.proto_name,
            );
            quote! {
                #[doc = #comment]
                pub const #name: u8 = #idx;
            }
        })
        .collect();
    quote! { #(#consts)* }
}

fn gen_method_names(service: &prost_build::Service) -> TokenStream {
    let names: Vec<_> = service
        .methods
        .iter()
        .map(|m| format!("{}.{}/{}", service.package, service.name, m.proto_name))
        .collect();
    let count = names.len();
    quote! {
        /// Full gRPC-style method names, indexed by method constant.
        pub const METHOD_NAMES: [&str; #count] = [#(#names),*];
    }
}

fn gen_server_trait(service: &prost_build::Service) -> TokenStream {
    let trait_name = format_ident!("{}", service.name);
    let trait_doc = format!(
        "Server trait for the `{}.{}` service.\n\nGenerated by ws-mux build support.",
        service.package, service.name,
    );

    let native_methods = gen_trait_methods(service, false);
    let wasm_methods = gen_trait_methods(service, true);

    quote! {
        #[cfg(not(target_arch = "wasm32"))]
        #[doc = #trait_doc]
        pub trait #trait_name: Clone + Send + Sync + 'static {
            #native_methods
        }

        #[cfg(target_arch = "wasm32")]
        #[doc = #trait_doc]
        pub trait #trait_name: Clone + 'static {
            #wasm_methods
        }
    }
}

fn gen_trait_methods(service: &prost_build::Service, wasm: bool) -> TokenStream {
    let methods: Vec<_> = service
        .methods
        .iter()
        .map(|method| {
            let fn_name = format_ident!("{}", method.name);
            let req_type: TokenStream = method.input_type.parse().expect("valid type path");
            let resp_type: TokenStream = method.output_type.parse().expect("valid type path");

            if method.server_streaming {
                let stream_type_name = format_ident!("{}Stream", to_upper_camel_case(&method.name));
                if wasm {
                    quote! {
                        type #stream_type_name: ::futures_core::Stream<
                            Item = Result<#resp_type, ws_mux::Error>,
                        > + 'static;

                        fn #fn_name(
                            &self,
                            req: #req_type,
                        ) -> impl ::std::future::Future<
                            Output = Result<Self::#stream_type_name, ws_mux::Error>,
                        >;
                    }
                } else {
                    quote! {
                        type #stream_type_name: ::futures_core::Stream<
                            Item = Result<#resp_type, ws_mux::Error>,
                        > + Send + 'static;

                        fn #fn_name(
                            &self,
                            req: #req_type,
                        ) -> impl ::std::future::Future<
                            Output = Result<Self::#stream_type_name, ws_mux::Error>,
                        > + Send;
                    }
                }
            } else if method.client_streaming {
                if wasm {
                    quote! {
                        fn #fn_name(
                            &self,
                            messages: Vec<#req_type>,
                        ) -> impl ::std::future::Future<
                            Output = Result<#resp_type, ws_mux::Error>,
                        >;
                    }
                } else {
                    quote! {
                        fn #fn_name(
                            &self,
                            messages: Vec<#req_type>,
                        ) -> impl ::std::future::Future<
                            Output = Result<#resp_type, ws_mux::Error>,
                        > + Send;
                    }
                }
            } else if wasm {
                quote! {
                    fn #fn_name(
                        &self,
                        req: #req_type,
                    ) -> impl ::std::future::Future<
                        Output = Result<#resp_type, ws_mux::Error>,
                    >;
                }
            } else {
                quote! {
                    fn #fn_name(
                        &self,
                        req: #req_type,
                    ) -> impl ::std::future::Future<
                        Output = Result<#resp_type, ws_mux::Error>,
                    > + Send;
                }
            }
        })
        .collect();

    quote! { #(#methods)* }
}

#[allow(clippy::too_many_lines)]
fn gen_dispatch(service: &prost_build::Service) -> TokenStream {
    let trait_name = format_ident!("{}", service.name);

    let arms: Vec<_> = service
        .methods
        .iter()
        .map(|method| {
            let method_const = format_ident!("METHOD_{}", to_screaming_snake_case(&method.name));
            let fn_name = format_ident!("{}", method.name);
            let req_type: TokenStream = method.input_type.parse().expect("valid type path");

            if method.server_streaming {
                quote! {
                    #method_const => {
                        let req = #req_type::decode(payload)
                            .map_err(ws_mux::Error::from)?;
                        match service.#fn_name(req).await {
                            Ok(stream) => {
                                use ::futures_core::Stream;
                                let mut stream = ::std::pin::pin!(stream);
                                loop {
                                    match ::std::future::poll_fn(|cx| stream.as_mut().poll_next(cx)).await {
                                        Some(Ok(msg)) => {
                                            let frame = ws_mux::Frame {
                                                stream_id,
                                                flags: ws_mux::flags::DATA,
                                                payload: msg.encode_to_vec(),
                                            };
                                            sink.send_frame(frame).await?;
                                        }
                                        Some(Err(e)) => {
                                            let frame = ws_mux::Frame {
                                                stream_id,
                                                flags: ws_mux::flags::RST,
                                                payload: ws_mux::frame::build_rst_payload(
                                                    ws_mux::error::code::INTERNAL,
                                                    &e.to_string(),
                                                ),
                                            };
                                            sink.send_frame(frame).await?;
                                            return Ok(());
                                        }
                                        None => break,
                                    }
                                }
                                let frame = ws_mux::Frame {
                                    stream_id,
                                    flags: ws_mux::flags::DATA | ws_mux::flags::END,
                                    payload: vec![],
                                };
                                sink.send_frame(frame).await?;
                            }
                            Err(e) => {
                                let frame = ws_mux::Frame {
                                    stream_id,
                                    flags: ws_mux::flags::RST,
                                    payload: ws_mux::frame::build_rst_payload(
                                        ws_mux::error::code::INTERNAL,
                                        &e.to_string(),
                                    ),
                                };
                                sink.send_frame(frame).await?;
                            }
                        }
                    }
                }
            } else if method.client_streaming {
                quote! {
                    #method_const => {
                        let mut cursor = payload;
                        let mut messages = Vec::new();
                        while !cursor.is_empty() {
                            let msg = #req_type::decode_length_delimited(&mut cursor)
                                .map_err(ws_mux::Error::from)?;
                            messages.push(msg);
                        }
                        match service.#fn_name(messages).await {
                            Ok(resp) => {
                                let frame = ws_mux::Frame {
                                    stream_id,
                                    flags: ws_mux::flags::DATA | ws_mux::flags::END,
                                    payload: resp.encode_to_vec(),
                                };
                                sink.send_frame(frame).await?;
                            }
                            Err(e) => {
                                let frame = ws_mux::Frame {
                                    stream_id,
                                    flags: ws_mux::flags::RST,
                                    payload: ws_mux::frame::build_rst_payload(
                                        ws_mux::error::code::INTERNAL,
                                        &e.to_string(),
                                    ),
                                };
                                sink.send_frame(frame).await?;
                            }
                        }
                    }
                }
            } else {
                quote! {
                    #method_const => {
                        let req = #req_type::decode(payload)
                            .map_err(ws_mux::Error::from)?;
                        match service.#fn_name(req).await {
                            Ok(resp) => {
                                let frame = ws_mux::Frame {
                                    stream_id,
                                    flags: ws_mux::flags::DATA | ws_mux::flags::END,
                                    payload: resp.encode_to_vec(),
                                };
                                sink.send_frame(frame).await?;
                            }
                            Err(e) => {
                                let frame = ws_mux::Frame {
                                    stream_id,
                                    flags: ws_mux::flags::RST,
                                    payload: ws_mux::frame::build_rst_payload(
                                        ws_mux::error::code::INTERNAL,
                                        &e.to_string(),
                                    ),
                                };
                                sink.send_frame(frame).await?;
                            }
                        }
                    }
                }
            }
        })
        .collect();

    quote! {
        /// Dispatch an OPEN frame to the appropriate service method.
        ///
        /// Generated by ws-mux build support. Implements `ws_mux::ServiceDispatch`.
        pub async fn dispatch<S: #trait_name>(
            service: &S,
            stream_id: u32,
            method_index: u8,
            payload: &[u8],
            sink: &dyn ws_mux::ServerSink,
        ) -> Result<(), ws_mux::Error> {
            use ::prost::Message;
            match method_index {
                #(#arms)*
                _ => {
                    let frame = ws_mux::Frame {
                        stream_id,
                        flags: ws_mux::flags::RST,
                        payload: ws_mux::frame::build_rst_payload(
                            ws_mux::error::code::UNIMPLEMENTED,
                            "unknown method",
                        ),
                    };
                    sink.send_frame(frame).await?;
                }
            }
            Ok(())
        }
    }
}

fn gen_dispatcher(service: &prost_build::Service) -> TokenStream {
    let trait_name = format_ident!("{}", service.name);
    let dispatcher_name = format_ident!("{}Dispatcher", service.name);
    let dispatcher_doc = format!(
        "Wrapper that implements `ws_mux::ServiceDispatch` for any `{}` impl.\n\nGenerated by ws-mux build support.",
        service.name,
    );

    quote! {
        #[doc = #dispatcher_doc]
        #[derive(Clone)]
        pub struct #dispatcher_name<S: #trait_name> {
            service: S,
        }

        impl<S: #trait_name> #dispatcher_name<S> {
            pub fn new(service: S) -> Self {
                Self { service }
            }
        }

        impl<S: #trait_name> ws_mux::ServiceDispatch for #dispatcher_name<S> {
            async fn dispatch(
                &self,
                stream_id: u32,
                method_index: u8,
                payload: &[u8],
                sink: &dyn ws_mux::ServerSink,
            ) -> Result<(), ws_mux::Error> {
                dispatch(&self.service, stream_id, method_index, payload, sink).await
            }
        }
    }
}

fn gen_client(service: &prost_build::Service) -> TokenStream {
    let client_name = format_ident!("{}Client", service.name);
    let client_doc = format!(
        "Typed ws-mux client for the `{}.{}` service.\n\nGenerated by ws-mux build support.",
        service.package, service.name,
    );

    let methods: Vec<_> = service
        .methods
        .iter()
        .map(|method| {
            let fn_name = format_ident!("{}", method.name);
            let method_const = format_ident!("METHOD_{}", to_screaming_snake_case(&method.name));
            let req_type: TokenStream = method.input_type.parse().expect("valid type path");
            let resp_type: TokenStream = method.output_type.parse().expect("valid type path");

            if method.server_streaming {
                quote! {
                    pub async fn #fn_name(
                        &self,
                        req: #req_type,
                    ) -> Result<ws_mux::Streaming, ws_mux::Error> {
                        self.channel.server_streaming(#method_const, &req).await
                    }
                }
            } else if method.client_streaming {
                quote! {
                    pub async fn #fn_name(
                        &self,
                    ) -> Result<(ws_mux::StreamingSender, ws_mux::ResponseFuture), ws_mux::Error> {
                        self.channel.client_streaming(#method_const).await
                    }
                }
            } else {
                quote! {
                    pub async fn #fn_name(
                        &self,
                        req: #req_type,
                    ) -> Result<#resp_type, ws_mux::Error> {
                        self.channel.unary(#method_const, &req).await
                    }
                }
            }
        })
        .collect();

    quote! {
        #[doc = #client_doc]
        #[derive(Clone)]
        pub struct #client_name {
            channel: ws_mux::MuxChannel,
        }

        impl #client_name {
            /// Create a new client from an existing [`ws_mux::MuxChannel`].
            pub fn new(channel: ws_mux::MuxChannel) -> Self {
                Self { channel }
            }

            /// Get a reference to the underlying channel.
            pub fn channel(&self) -> &ws_mux::MuxChannel {
                &self.channel
            }

            #(#methods)*
        }
    }
}

fn to_snake_case(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::with_capacity(chars.len() + 4);
    for (i, ch) in chars.iter().copied().enumerate() {
        let prev = i.checked_sub(1).and_then(|j| chars.get(j).copied());
        let next = chars.get(i + 1).copied();
        if ch.is_uppercase() {
            let prev_is_lower_or_digit = prev.is_some_and(|c| c.is_lowercase() || c.is_ascii_digit());
            let prev_is_upper = prev.is_some_and(char::is_uppercase);
            let next_is_lower = next.is_some_and(char::is_lowercase);
            if i > 0 && (prev_is_lower_or_digit || (prev_is_upper && next_is_lower)) {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else if ch == '-' || ch == ' ' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_screaming_snake_case(s: &str) -> String {
    to_snake_case(s).to_uppercase()
}

fn to_upper_camel_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    upper + &chars.as_str().to_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}
