use crate::error::{self, Error};
use crate::frame::{self, Frame, flags};

/// Trait for sending raw bytes over a WebSocket (server-side).
#[cfg(not(target_arch = "wasm32"))]
pub trait WsSink {
    fn send(&self, data: Vec<u8>) -> impl std::future::Future<Output = Result<(), Error>> + Send;
}

/// Trait for sending raw bytes over a WebSocket (server-side, wasm32 variant).
#[cfg(target_arch = "wasm32")]
pub trait WsSink {
    fn send(&self, data: Vec<u8>) -> impl std::future::Future<Output = Result<(), Error>>;
}

/// Trait generated by ws-mux codegen for each protobuf service.
///
/// The generated `dispatch` function calls the appropriate service method
/// based on the method index in the OPEN frame.
#[cfg(not(target_arch = "wasm32"))]
pub trait ServiceDispatch: Send + Sync + 'static {
    fn dispatch(
        &self,
        stream_id: u32,
        method_index: u8,
        payload: &[u8],
        sink: &dyn ServerSink,
    ) -> impl std::future::Future<Output = Result<(), Error>> + Send;
}

/// Trait generated by ws-mux codegen for each protobuf service (wasm32 variant).
#[cfg(target_arch = "wasm32")]
pub trait ServiceDispatch: 'static {
    fn dispatch(
        &self,
        stream_id: u32,
        method_index: u8,
        payload: &[u8],
        sink: &dyn ServerSink,
    ) -> impl std::future::Future<Output = Result<(), Error>>;
}

/// Server-side sink that can send frames.
///
/// This is object-safe (unlike `WsSink`) so it can be passed as `&dyn`.
#[cfg(not(target_arch = "wasm32"))]
pub trait ServerSink: Send + Sync {
    fn send_frame(
        &self,
        frame: Frame,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), Error>> + Send + '_>>;
}

/// Server-side sink that can send frames (wasm32 variant, no Send).
#[cfg(target_arch = "wasm32")]
pub trait ServerSink {
    fn send_frame(
        &self,
        frame: Frame,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), Error>> + '_>>;
}

/// Blanket impl: anything that can send raw bytes can be a ServerSink.
#[cfg(not(target_arch = "wasm32"))]
impl<T: WsSink + Send + Sync> ServerSink for T {
    fn send_frame(
        &self,
        frame: Frame,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), Error>> + Send + '_>> {
        Box::pin(async move { self.send(frame.encode()).await })
    }
}

/// Blanket impl: anything that can send raw bytes can be a ServerSink (wasm32).
#[cfg(target_arch = "wasm32")]
impl<T: WsSink> ServerSink for T {
    fn send_frame(
        &self,
        frame: Frame,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), Error>> + '_>> {
        Box::pin(async move { self.send(frame.encode()).await })
    }
}

/// Maximum accumulated payload size per client-streaming RPC (4 MiB).
const MAX_CLIENT_STREAM_PAYLOAD: usize = 4 * 1024 * 1024;
/// Maximum accumulated payload size across all active client streams (64 MiB).
const MAX_TOTAL_CLIENT_STREAM_PAYLOAD: usize = 64 * 1024 * 1024;
/// Idle timeout for active client-streaming RPCs.
const CLIENT_STREAM_IDLE_TIMEOUT_MS: u64 = 60_000;

/// Maximum number of concurrently open client-streaming RPCs.
const MAX_ACTIVE_CLIENT_STREAMS: usize = 256;

fn varint_len(mut v: u64) -> usize {
    let mut len = 1usize;
    while v >= 0x80 {
        v >>= 7;
        len += 1;
    }
    len
}

fn delimited_chunk_len(payload_len: usize) -> usize {
    varint_len(payload_len as u64).saturating_add(payload_len)
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

/// Accumulation state for client-streaming RPCs.
///
/// Tracks partial streams where the client has sent OPEN but not yet END.
/// This state is serializable for DO hibernation.
#[derive(Default, Debug, Clone)]
pub struct StreamState {
    /// Active client-streaming streams: stream_id -> (method_index, accumulated payload bytes).
    pub active: std::collections::HashMap<u32, (u8, Vec<u8>)>,
    /// Last observed activity timestamp per stream (`unix_ms`).
    pub last_activity_ms: std::collections::HashMap<u32, u64>,
    /// Total buffered bytes across all active client streams.
    pub total_active_payload_bytes: usize,
}

impl StreamState {
    fn insert_stream(&mut self, stream_id: u32, method_index: u8, payload: Vec<u8>, now_ms: u64) {
        self.total_active_payload_bytes = self
            .total_active_payload_bytes
            .saturating_add(payload.len());
        self.active.insert(stream_id, (method_index, payload));
        self.last_activity_ms.insert(stream_id, now_ms);
    }

    fn remove_stream(&mut self, stream_id: u32) -> Option<(u8, Vec<u8>)> {
        let removed = self.active.remove(&stream_id);
        if let Some((_, payload)) = &removed {
            self.total_active_payload_bytes = self
                .total_active_payload_bytes
                .saturating_sub(payload.len());
        }
        self.last_activity_ms.remove(&stream_id);
        removed
    }

    fn prune_idle_streams(&mut self, now_ms: u64) -> Vec<u32> {
        let mut expired = Vec::new();
        for (&stream_id, &last) in &self.last_activity_ms {
            if now_ms.saturating_sub(last) > CLIENT_STREAM_IDLE_TIMEOUT_MS {
                expired.push(stream_id);
            }
        }
        for stream_id in &expired {
            let _ = self.remove_stream(*stream_id);
        }
        expired
    }
}

/// Handle a single incoming WebSocket message (one frame) on the server side.
///
/// This is the DO-compatible entry point: stateless per-message processing
/// with `StreamState` for client-streaming accumulation.
async fn handle_decoded_frame<S: ServiceDispatch>(
    service: &S,
    frame: Frame,
    sink: &dyn ServerSink,
    streams: &mut StreamState,
) -> Result<(), Error> {
    let now = now_ms();
    for expired_stream_id in streams.prune_idle_streams(now) {
        let rst = Frame {
            stream_id: expired_stream_id,
            flags: flags::RST,
            payload: frame::build_rst_payload(error::code::CANCELLED, "client stream idle timeout"),
        };
        sink.send_frame(rst).await?;
    }

    if frame.is_rst() {
        // Client cancelled a stream. Clean up any accumulation state.
        let _ = streams.remove_stream(frame.stream_id);
        return Ok(());
    }

    if frame.is_open() {
        let (method_index, payload) = frame::parse_open_payload(&frame.payload)?;

        if frame.is_end() {
            // Unary or server-streaming: OPEN|END — dispatch immediately.
            service
                .dispatch(frame.stream_id, method_index, payload, sink)
                .await?;
        } else {
            // Client-streaming: OPEN without END — start accumulating.
            if streams.active.contains_key(&frame.stream_id) {
                let rst = Frame {
                    stream_id: frame.stream_id,
                    flags: flags::RST,
                    payload: frame::build_rst_payload(
                        error::code::INVALID_ARGUMENT,
                        "duplicate OPEN for active stream",
                    ),
                };
                sink.send_frame(rst).await?;
                return Ok(());
            }
            if streams.active.len() >= MAX_ACTIVE_CLIENT_STREAMS {
                let rst = Frame {
                    stream_id: frame.stream_id,
                    flags: flags::RST,
                    payload: frame::build_rst_payload(
                        error::code::UNAVAILABLE,
                        "too many active client streams",
                    ),
                };
                sink.send_frame(rst).await?;
                return Ok(());
            }
            let initial_chunk_len = if payload.is_empty() {
                0
            } else {
                delimited_chunk_len(payload.len())
            };
            if initial_chunk_len > MAX_CLIENT_STREAM_PAYLOAD {
                let rst = Frame {
                    stream_id: frame.stream_id,
                    flags: flags::RST,
                    payload: frame::build_rst_payload(
                        error::code::INVALID_ARGUMENT,
                        "client stream payload too large",
                    ),
                };
                sink.send_frame(rst).await?;
                return Ok(());
            }
            if streams
                .total_active_payload_bytes
                .saturating_add(initial_chunk_len)
                > MAX_TOTAL_CLIENT_STREAM_PAYLOAD
            {
                let rst = Frame {
                    stream_id: frame.stream_id,
                    flags: flags::RST,
                    payload: frame::build_rst_payload(
                        error::code::UNAVAILABLE,
                        "aggregate client stream payload too large",
                    ),
                };
                sink.send_frame(rst).await?;
                return Ok(());
            }
            // Length-delimit the initial payload (if any) so the accumulated
            // buffer is compatible with decode_length_delimited in dispatch.
            let mut buf = Vec::with_capacity(initial_chunk_len);
            if !payload.is_empty() {
                prost::encoding::encode_varint(payload.len() as u64, &mut buf);
                buf.extend_from_slice(payload);
            }
            streams.insert_stream(frame.stream_id, method_index, buf, now);
        }
        return Ok(());
    }

    if frame.is_data() {
        if let Some((method_index, mut buf)) = streams.remove_stream(frame.stream_id) {
            if frame.is_end() && frame.payload.is_empty() {
                // DATA|END with empty payload is an end marker, not an extra empty message.
                service
                    .dispatch(frame.stream_id, method_index, &buf, sink)
                    .await?;
                return Ok(());
            }

            if frame.payload.is_empty() {
                // Ignore empty DATA chunks that are not terminators.
                streams.insert_stream(frame.stream_id, method_index, buf, now);
                return Ok(());
            }

            let added = delimited_chunk_len(frame.payload.len());
            let new_len = buf.len().saturating_add(added);
            if new_len > MAX_CLIENT_STREAM_PAYLOAD {
                let rst = Frame {
                    stream_id: frame.stream_id,
                    flags: flags::RST,
                    payload: frame::build_rst_payload(
                        error::code::INVALID_ARGUMENT,
                        "client stream payload too large",
                    ),
                };
                sink.send_frame(rst).await?;
                return Ok(());
            }

            if streams.total_active_payload_bytes.saturating_add(new_len)
                > MAX_TOTAL_CLIENT_STREAM_PAYLOAD
            {
                let rst = Frame {
                    stream_id: frame.stream_id,
                    flags: flags::RST,
                    payload: frame::build_rst_payload(
                        error::code::UNAVAILABLE,
                        "aggregate client stream payload too large",
                    ),
                };
                sink.send_frame(rst).await?;
                return Ok(());
            }

            // Length-delimit each message so the accumulated buffer
            // is compatible with decode_length_delimited in dispatch.
            prost::encoding::encode_varint(frame.payload.len() as u64, &mut buf);
            buf.extend_from_slice(&frame.payload);

            if frame.is_end() {
                service
                    .dispatch(frame.stream_id, method_index, &buf, sink)
                    .await?;
                return Ok(());
            }

            streams.insert_stream(frame.stream_id, method_index, buf, now);
            return Ok(());
        }

        // DATA for unknown stream — send RST.
        let rst = Frame {
            stream_id: frame.stream_id,
            flags: flags::RST,
            payload: frame::build_rst_payload(
                error::code::INVALID_ARGUMENT,
                "DATA for unknown stream",
            ),
        };
        sink.send_frame(rst).await?;
        return Ok(());
    } else {
        let rst = Frame {
            stream_id: frame.stream_id,
            flags: flags::RST,
            payload: frame::build_rst_payload(
                error::code::INVALID_ARGUMENT,
                "unknown or unsupported frame flags",
            ),
        };
        sink.send_frame(rst).await?;
    }

    Ok(())
}

/// Handle a single incoming WebSocket message (one frame) on the server side.
///
/// This is the DO-compatible entry point: stateless per-message processing
/// with `StreamState` for client-streaming accumulation.
pub async fn handle_frame<S: ServiceDispatch>(
    service: &S,
    data: &[u8],
    sink: &dyn ServerSink,
    streams: &mut StreamState,
) -> Result<(), Error> {
    let frame = Frame::decode(data)?;
    handle_decoded_frame(service, frame, sink, streams).await
}

/// Handle a single incoming WebSocket message on a **bidirectional** connection.
///
/// A bidirectional connection carries both client-initiated RPCs (outgoing
/// calls via `channel`) and server-dispatched RPCs (incoming requests via
/// `service`) on the same WebSocket.
///
/// Routing rule:
/// - Frames for stream IDs initiated by this side are responses to our pending
///   client RPCs → routed to `channel` via
///   [`MuxChannel::route_frame`](crate::client::MuxChannel::route_frame).
/// - Frames for stream IDs initiated by the remote side are inbound RPC
///   traffic → dispatched to `service` via [`handle_frame`].
///
/// This is the key primitive for Durable Object hibernation, where a single
/// WebSocket serves both directions and messages arrive via `websocket_message`.
#[cfg(feature = "client")]
pub async fn handle_bidi_frame<S: ServiceDispatch>(
    data: &[u8],
    service: &S,
    channel: &crate::client::MuxChannel,
    sink: &dyn ServerSink,
    streams: &mut StreamState,
) -> Result<(), Error> {
    let frame = Frame::decode(data)?;
    if channel.is_local_stream_id(frame.stream_id) {
        // Response to one of our client RPCs — route to pending stream.
        channel.route_frame(frame).await;
        Ok(())
    } else {
        // Request stream initiated by remote side — dispatch server-side.
        handle_decoded_frame(service, frame, sink, streams).await
    }
}

/// Run the server loop over a WebSocket transport (native async use).
///
/// Reads messages from `recv`, dispatches each via `handle_frame`,
/// and sends responses through `sink`.
#[cfg(not(target_arch = "wasm32"))]
pub async fn serve<S, Recv, Sink>(service: S, mut recv: Recv, sink: Sink) -> Result<(), Error>
where
    S: ServiceDispatch + Clone,
    Recv: WsRecv,
    Sink: WsSink + Send + Sync + Clone + 'static,
{
    let mut streams = StreamState::default();

    loop {
        let msg = match recv.recv().await {
            Ok(Some(data)) => data,
            Ok(None) => break,
            Err(e) => {
                tracing::warn!(error = %e, "ws recv error");
                break;
            }
        };

        let service = service.clone();
        let sink = sink.clone();

        // For unary RPCs we could handle inline, but for server-streaming
        // we need to spawn so the serve loop can continue accepting frames.
        // Client-streaming accumulation must happen on the main loop to maintain StreamState.
        let frame = match Frame::decode(&msg) {
            Ok(f) => f,
            Err(e) => {
                tracing::warn!(error = %e, "bad frame");
                continue;
            }
        };

        if frame.is_open() && frame.is_end() {
            // Unary or server-streaming request — can be dispatched concurrently.
            let (method_index, payload) = match frame::parse_open_payload(&frame.payload) {
                Ok(v) => v,
                Err(e) => {
                    tracing::warn!(error = %e, "bad OPEN payload");
                    continue;
                }
            };
            let payload = payload.to_vec();
            tokio::spawn(async move {
                if let Err(e) = service
                    .dispatch(frame.stream_id, method_index, &payload, &sink)
                    .await
                {
                    tracing::warn!(error = %e, stream_id = frame.stream_id, "dispatch error");
                }
            });
        } else {
            // Client-streaming: needs sequential state management.
            if let Err(e) = handle_decoded_frame(&service, frame, &sink, &mut streams).await {
                tracing::warn!(error = %e, "handle_frame error");
            }
        }
    }

    Ok(())
}

/// Trait for receiving WebSocket messages.
#[cfg(not(target_arch = "wasm32"))]
pub trait WsRecv: Send + 'static {
    fn recv(&mut self) -> impl std::future::Future<Output = Result<Option<Vec<u8>>, Error>> + Send;
}

/// Native WebSocket sink backed by a tokio-tungstenite split write half.
#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
pub struct NativeWsSink<S> {
    write: std::sync::Arc<tokio::sync::Mutex<S>>,
}

#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
impl<S> Clone for NativeWsSink<S> {
    fn clone(&self) -> Self {
        Self {
            write: self.write.clone(),
        }
    }
}

#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
impl<S> NativeWsSink<S> {
    pub fn new(write: S) -> Self {
        Self {
            write: std::sync::Arc::new(tokio::sync::Mutex::new(write)),
        }
    }
}

#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
impl<S> WsSink for NativeWsSink<S>
where
    S: futures_util::Sink<
            tokio_tungstenite::tungstenite::Message,
            Error = tokio_tungstenite::tungstenite::Error,
        > + Unpin
        + Send
        + Sync
        + 'static,
{
    async fn send(&self, data: Vec<u8>) -> Result<(), Error> {
        use futures_util::SinkExt;

        self.write
            .lock()
            .await
            .send(tokio_tungstenite::tungstenite::Message::Binary(data.into()))
            .await
            .map_err(|e| Error::Io(std::io::Error::other(e)))
    }
}

/// Native WebSocket receiver backed by a tokio-tungstenite split read half.
#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
pub struct NativeWsRecv<S> {
    read: S,
}

#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
impl<S> NativeWsRecv<S> {
    pub fn new(read: S) -> Self {
        Self { read }
    }
}

#[cfg(all(feature = "native-client", not(target_arch = "wasm32")))]
impl<S> WsRecv for NativeWsRecv<S>
where
    S: futures_util::Stream<
            Item = Result<
                tokio_tungstenite::tungstenite::Message,
                tokio_tungstenite::tungstenite::Error,
            >,
        > + Unpin
        + Send
        + 'static,
{
    async fn recv(&mut self) -> Result<Option<Vec<u8>>, Error> {
        use futures_util::StreamExt;

        loop {
            match self.read.next().await {
                Some(Ok(tokio_tungstenite::tungstenite::Message::Binary(data))) => {
                    return Ok(Some(data.into()));
                }
                Some(Ok(tokio_tungstenite::tungstenite::Message::Close(_))) | None => {
                    return Ok(None);
                }
                Some(Ok(_)) => continue, // ignore text, ping, pong
                Some(Err(e)) => return Err(Error::Io(std::io::Error::other(e))),
            }
        }
    }
}

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
    use super::*;
    use std::sync::Arc;
    use tokio::sync::Mutex;

    #[derive(Clone, Default)]
    struct NoopService;

    impl ServiceDispatch for NoopService {
        async fn dispatch(
            &self,
            _stream_id: u32,
            _method_index: u8,
            _payload: &[u8],
            _sink: &dyn ServerSink,
        ) -> Result<(), Error> {
            Ok(())
        }
    }

    #[derive(Clone, Default)]
    struct TestSink(Arc<Mutex<Vec<Frame>>>);

    impl WsSink for TestSink {
        async fn send(&self, data: Vec<u8>) -> Result<(), Error> {
            let frame = Frame::decode(&data)?;
            self.0.lock().await.push(frame);
            Ok(())
        }
    }

    #[test]
    fn prune_idle_streams_reclaims_payload_bytes() {
        let mut state = StreamState::default();
        state.insert_stream(1, 0, vec![0; 10], 100);
        state.insert_stream(3, 0, vec![0; 20], 200);

        let expired = state.prune_idle_streams(100 + CLIENT_STREAM_IDLE_TIMEOUT_MS + 1);
        assert_eq!(expired, vec![1]);
        assert!(state.active.contains_key(&3));
        assert!(!state.active.contains_key(&1));
        assert_eq!(state.total_active_payload_bytes, 20);
    }

    #[tokio::test]
    async fn aggregate_cap_rejects_new_open_stream() {
        let service = NoopService;
        let sink = TestSink::default();
        let mut state = StreamState {
            total_active_payload_bytes: MAX_TOTAL_CLIENT_STREAM_PAYLOAD,
            ..Default::default()
        };

        let frame = Frame {
            stream_id: 1,
            flags: flags::OPEN,
            payload: frame::build_open_payload(0, &[42]),
        };
        handle_frame(&service, &frame.encode(), &sink, &mut state)
            .await
            .expect("handle frame");

        let sent = sink.0.lock().await;
        assert!(sent.iter().any(|f| f.is_rst()));
        assert!(state.active.is_empty());
    }

    #[tokio::test]
    async fn prune_idle_streams_emits_rst_during_handle_frame() {
        let service = NoopService;
        let sink = TestSink::default();
        let mut state = StreamState::default();
        state.insert_stream(1, 0, vec![7], 0);

        let frame = Frame {
            stream_id: 9,
            flags: flags::OPEN | flags::END,
            payload: frame::build_open_payload(0, &[]),
        };
        handle_frame(&service, &frame.encode(), &sink, &mut state)
            .await
            .expect("handle frame");

        let sent = sink.0.lock().await;
        assert!(sent.iter().any(|f| f.stream_id == 1 && f.is_rst()));
        assert!(!state.active.contains_key(&1));
    }
}
